SECRET_KEY = "dev"
JWT_SECRET_KEY ="testing one",
JWT_TOKEN_LOCATION=["cookies"] ,
JWT_ACCESS_COOKIE_NAME="access_token",
JWT_COOKIE_SECURE=False,
JWT_COOKIE_CSRF_PROTECT=False,
JWT_COOKIE_SAMESITE="None"
